spring:
  application:
    name: mall-system

  profiles:
    default: local

server:
  port: 8080

mybatis:
  mapper-locations: classpath*:mapper/**/*.xml
  type-aliases-package: com.kakarot.mall
  configuration:
    map-underscore-to-camel-case: true

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

jwt:
  expiration: 86400

logging:
  level:
    root: info
    com.kakarot.mall: debug